<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ $label }} Report - {{ date('Y-m-d') }}</title>
    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=figtree:400,500,600,700&display=swap" rel="stylesheet" />
    <style>
        body {
            font-family: 'Figtree', sans-serif;
            color: #1e293b;
            background: #ffffff;
            margin: 0;
            padding: 40px;
            -webkit-print-color-adjust: exact;
        }
        .header {
            border-bottom: 2px solid #e2e8f0;
            padding-bottom: 20px;
            margin-bottom: 30px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        .title {
            font-size: 24px;
            font-weight: 700;
            color: #0f172a;
            margin: 0;
        }
        .meta {
            font-size: 13px;
            color: #64748b;
        }
        .filters {
            background-color: #f8fafc;
            border: 1px solid #e2e8f0;
            border-radius: 8px;
            padding: 15px;
            margin-bottom: 30px;
            font-size: 13px;
        }
        .filters h4 {
            margin: 0 0 8px 0;
            color: #334155;
            font-weight: 600;
        }
        .filters p {
            margin: 0;
            color: #64748b;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 12px;
            margin-bottom: 30px;
        }
        th {
            background-color: #f1f5f9;
            color: #475569;
            font-weight: 600;
            text-align: left;
            padding: 10px 12px;
            border-bottom: 2px solid #cbd5e1;
            text-transform: uppercase;
            font-size: 10px;
            letter-spacing: 0.5px;
        }
        td {
            padding: 10px 12px;
            border-bottom: 1px solid #e2e8f0;
            color: #334155;
            word-break: break-word;
        }
        tr:nth-child(even) {
            background-color: #f8fafc;
        }
        .stats {
            display: flex;
            gap: 20px;
            margin-bottom: 30px;
        }
        .stat-box {
            border: 1px solid #e2e8f0;
            border-radius: 8px;
            padding: 15px;
            flex: 1;
            background-color: #f8fafc;
        }
        .stat-val {
            font-size: 20px;
            font-weight: 700;
            color: #0f172a;
        }
        .stat-lbl {
            font-size: 11px;
            color: #64748b;
            text-transform: uppercase;
            letter-spacing: 0.5px;
            margin-top: 4px;
        }
        .footer {
            margin-top: 50px;
            border-top: 1px solid #e2e8f0;
            padding-top: 15px;
            text-align: center;
            font-size: 11px;
            color: #94a3b8;
        }
        .print-btn-bar {
            display: flex;
            justify-content: flex-end;
            margin-bottom: 20px;
        }
        .print-btn {
            background-color: #3b82f6;
            color: #ffffff;
            border: none;
            padding: 8px 16px;
            border-radius: 6px;
            font-weight: 600;
            font-size: 13px;
            cursor: pointer;
            box-shadow: 0 1px 3px rgba(0,0,0,0.1);
        }
        .print-btn:hover {
            background-color: #2563eb;
        }
        @media print {
            .print-btn-bar {
                display: none;
            }
            body {
                padding: 0;
            }
        }
    </style>
</head>
<body>

    <div class="print-btn-bar">
        <button class="print-btn" onclick="window.print()">Print Report / Save as PDF</button>
    </div>

    <div class="header">
        <div>
            <h1 class="title">{{ $label }} Report</h1>
            <div class="meta">Generated by {{ auth()->user()->name }} ({{ auth()->user()->email }})</div>
        </div>
        <div style="text-align: right;">
            <div style="font-size: 16px; font-weight: 700; color: #3b82f6;">DURALUX</div>
            <div class="meta">Date: {{ date('Y-m-d H:i') }}</div>
        </div>
    </div>

    <!-- Stats summary -->
    <div class="stats">
        <div class="stat-box">
            <div class="stat-val">{{ number_format($data->count()) }}</div>
            <div class="stat-lbl">Total Records Found</div>
        </div>
        <div class="stat-box">
            <div class="stat-val">{{ count($columns) }}</div>
            <div class="stat-lbl">Columns Exported</div>
        </div>
    </div>

    @if($filters['start_date'] || $filters['end_date'])
        <div class="filters">
            <h4>Active Query Filters</h4>
            <p>
                @if($filters['start_date'])
                    <strong>Start Date:</strong> {{ $filters['start_date'] }}
                @endif
                @if($filters['end_date'])
                    &nbsp;&nbsp;|&nbsp;&nbsp;<strong>End Date:</strong> {{ $filters['end_date'] }}
                @endif
            </p>
        </div>
    @endif

    <table>
        <thead>
            <tr>
                @foreach($headers as $header)
                    <th>{{ $header }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @forelse($data as $row)
                <tr>
                    @foreach($columns as $col)
                        <td>
                            @php
                                $val = $row->{$col};
                            @endphp
                            @if(is_array($val) || is_object($val))
                                <pre style="font-family: monospace; font-size: 10px; margin: 0; white-space: pre-wrap;">{{ json_encode($val, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) }}</pre>
                            @elseif(is_bool($val))
                                {{ $val ? 'TRUE' : 'FALSE' }}
                            @elseif(is_null($val))
                                <span style="color: #cbd5e1; font-style: italic;">null</span>
                            @else
                                {{ $val }}
                            @endif
                        </td>
                    @endforeach
                </tr>
            @empty
                <tr>
                    <td colspan="{{ count($columns) }}" style="text-align: center; color: #94a3b8; padding: 30px 0;">
                        No records matched your query filters.
                    </td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Duralux Enterprise Report Center &copy; {{ date('Y') }} All rights reserved.
    </div>

</body>
</html>
